### ISSUE TITLE
NC command not found

### ISSUE THREAD

**Issue by melzareix** [ufoscout/docker-compose-wait#1]
I was running this in my container using `node` image and I get `nc command not found` had to install netcat for it to work, I think using `curl` for pinging would be better

i.e 
`curl $host:$port`  instead of `nc -z -w1 $host $port`

**Comment by ufoscout** [comment]
Hi @melzareix 
'nc' is used in the script the check is a TCP port is open, 'curl' cannot be used for this purpose because it performs HTTP requests.

**Comment by ufoscout** [comment]
@melzareix 
I rewrote this utility in rust, now it does not require netcat any more.
