### ISSUE TITLE
Cannot download docker-compose-wait

### ISSUE THREAD

**Issue by zabahey** [ufoscout/docker-compose-wait#14]
I follow usage instructions but I got 500 error when build image from Docker from this step

Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait

What wrong with it?

**Comment by zabahey** [comment]
Maybe something wrong with Github during the time. Now everything works as usual.

**Comment by jonasbn** [comment]
Just for the record, there was a GitHub issue, ref: https://www.githubstatus.com/incidents/8x69vj1xyp9v
