### ISSUE TITLE
WAIT_SLEEP_INTERVAL not working

### ISSUE THREAD

**Issue by primeapple** [ufoscout/docker-compose-wait#18]
Hi,
thanks for this amazing app! I relly like the documentation, it helped me to integrate your script into my docker-compose application.

However, I found, that the `WAIT_SLEEP_INTERVAL` environment variable doesn't change anything. It always defaults to 1.

After that I looked into your integration test and there were no tests, where you tested a `WAIT_SLEEP_INTERVAL` different from 1.

Could you please investigate this?

Have a great day!

**Comment by ufoscout** [comment]
Hi @primeapple 
it seems to me that it is used as expected.
https://github.com/ufoscout/docker-compose-wait/blob/b3859264253fb9994e6c16e3bce5f3f67f773f9c/src/lib.rs#L60

I added an integration test to verify it:
```rust
#[test]
fn should_sleep_the_specified_time_between_checks() {
    let start = Instant::now();
    let mut sleeper = MillisSleeper::default();
    wait::wait(&mut sleeper, &new_config("198.19.255.255:1", 2_000, 0, 0, 10, 1), &mut on_timeout);
    let elapsed = millis_elapsed(start);
    assert!(elapsed >= 2010); // attemps one connection and fails after 1000ms; then sleeps 10ms; finally connects again and fails after additional 1000ms
    assert!(elapsed < 3000);
}
```

**Comment by primeapple** [comment]
I'm very sorry, I used an old version, where sleeping was not working yet.  
This is resolved. However, I experienced another problem. For this, please see issue #19
