### ISSUE TITLE
What about wait for existence of a file?

### ISSUE THREAD

**Issue by sharifzadesina** [ufoscout/docker-compose-wait#20]
Sometimes, like when we are initializing database, the port is accessible but our database is not yet initialized, so we need to wait for database file creation.
This will be a simple feature but a useful one.

**Comment by ufoscout** [comment]
@sharifzadesina 
I am sorry for the late reply, I would like to keep this utility as small as possible in terms of both features and configuration options. Anyway, if you propose a PR that does not introduce external dependencies, I would indeed take it into account.

**Comment by edumco** [comment]
@sharifzadesina This sound like a similar utility that could be implemented completely independently from `docker-compose-wait` like a second command (maybe `wait-file`) that could be released as another package (crate ?).

This would keep the `wait` simple, small, ultra-fast and reliable and at the same time could extend options for another use cases.

@ufoscout this can be done inside this code base or should be made in another repository?

**Comment by ufoscout** [comment]
@edumco 
As said before, a PR would be welcome for this one.

**Comment by sharifzadesina** [comment]
@ufoscout I already did it both on one package.
https://github.com/elegantweb/docker-wait

They are bot "waiting" so it is better to be on the same package.
