### ISSUE TITLE
Using exec instead of &&

### ISSUE THREAD

**Issue by SamMousa** [ufoscout/docker-compose-wait#29]
It would be nice to support syntax that uses `exec` instead of a subshell.

The syntax for usage would be simple:
```
entrypoint: [
    "wait",
    "--",
    "myApp"
]
```

That way no shell is needed and signal handling becomes easier for the app since there's no longer a shell in between.

**Comment by ufoscout** [comment]
Partially duplicate of #27 
Let's continue the discussion there.
