### ISSUE TITLE
Better debugging ability

### ISSUE THREAD

**Issue by anlek** [ufoscout/docker-compose-wait#4]
I'm trying to set up `wait` on my own docker container system, and I want to see if `wait` is running and what it's doing, but there is no way to make `wait` more verbose. Any chance you can add a `-v` to give a more verbose output?

Thanks in advance,
Andrew

**Comment by anlek** [comment]
Hmm, I think I might have made a mistake, it seems if you run `wait` it's an Ubuntu command, you actually have to specify the exact path to the executable.  I renamed the file to `service-wait` to make things a bit more clear for myself.

I still think it would be nice to have a verbose setting so you can see what the defaults are for the other options as well as what it actually read in the WAIT_HOSTS env variable. (as it seems to test one at a time, making it seem like it only picked up the first variable).

**Comment by ufoscout** [comment]
@anlek 
release 2.3.0 logs the configuration at startup:
```
Docker-compose-wait starting with configuration:
------------------------------------------------
 - Hosts to be waiting for: [postgres:5432, mysql:3306, mongo:27017]
 - Timeout before failure: 30 seconds 
 - Sleeping time before checking for hosts availability: 5 seconds
 - Sleeping time once all hosts are available: 0 seconds
------------------------------------------------
```
Does it fix your request?

**Comment by anlek** [comment]
Sorry, I somehow missed the notification, I'll test this week and get back to you!
Thanks for the response though!

**Comment by ufoscout** [comment]
I guess this is ok now
