### ISSUE TITLE
Configure the sleep time

### ISSUE THREAD

**Issue by adriangalera** [ufoscout/docker-compose-wait#6]
Checking the code I saw that it's hardcoded to 1 second, I think it'd be easy and useful to configure the sleep time via environment variable!

Great work! Thanks

**Comment by ufoscout** [comment]
@adriangalera 
good point!
I'll do it for sure as soon as I have some time for it, in the meantime, feel free to send a PR :+1:

**Comment by ufoscout** [comment]
Fixed by #7
