### ISSUE TITLE
[BUG] WAIT_COMMAND does not work correctly

### ISSUE THREAD

**Issue by WagnerPMC** [ufoscout/docker-compose-wait#77]
Hello,

I notice that the executable command is inserted into the arguments of the same executable command:
https://github.com/ufoscout/docker-compose-wait/blob/48b2683918548a15885a2e6d4fb93a6997119947/src/lib.rs#L144-L151

In this way, it turns out that the conditional "**hello man**" command turns into the "**hello hello man**" command.
To prevent this from happening, we need to remove the first element of the vector from the argv variable, in the same place.

Quick fix:
```rust
let mut argv = shell_words::split(&command_string)?;

Ok(Some((
    Command {
        program: argv.remove(0),
        argv,
    },
    command_string,
)))
```

If it's a hassle, I can create a PR for a quick fix - just let me know.

**Comment by ufoscout** [comment]
Fixed by #78
